# Generated by Django 3.2.13 on 2022-05-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_pio4ly', upload_to='images/'),
        ),
    ]
